name: Run Test

on: pull_request

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      # Fetch all repository details (Including tag for semver).
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: "^1.19"

      # Run all test in Repo
      - name: Run Test
        shell: bash
        run: |
          make unit-test
